// const arr = [1000, 900, 800, 700, 600, 500, 400, 300, 200, 100];
$(document).ready(function () {
	$('.minus').click(function () {
		var $input = $(this).parent().find('input');
		var count = parseInt($input.val()) - 1;
		count = count < 1 ? 1 : count;
		$input.val(count);
		$input.change();
		return false;
	});
	$('.plus').click(function () {
		var $input = $(this).parent().find('input');
		$input.val(parseInt($input.val()) + 1);
		$input.change();
		return false;
	});

	let $cost = $('.price__num');
	let $inputP = $('.input');
	let $num = $('.price-value__num');
	$('.price-list__item').click(function () {
		let currentCost = parseInt($cost.text());
		let currentInput = parseInt($inputP.text());

		$num.text(currentCost * currentInput);
	});




	$('.price-list__item1').click(function () {
		$(".price-cost__num1").css("display", "flex");
		$(".price-cost__num2").css("display", "none");
		$(".price-cost__num3").css("display", "none");
		$(".price-cost__num4").css("display", "none");
		$(".price-cost__num5").css("display", "none");
		$(".price-cost__num6").css("display", "none");
		$(".price-cost__num7").css("display", "none");
		$(".price-cost__num8").css("display", "none");
		$(".price-cost__num9").css("display", "none");
		$(".price-cost__num10").css("display", "none");
		$(".price-list__item1").toggleClass("price-item");
		$(".price-list__item2").removeClass("price-item");
		$(".price-list__item3").removeClass("price-item");
		$(".price-list__item4").removeClass("price-item");
		$(".price-list__item5").removeClass("price-item");
		$(".price-list__item6").removeClass("price-item");
		$(".price-list__item7").removeClass("price-item");
		$(".price-list__item8").removeClass("price-item");
		$(".price-list__item9").removeClass("price-item");
		$(".price-list__item10").removeClass("price-item");
	});
	$('.price-list__item2').click(function () {
		$(".price-cost__num2").css("display", "flex");
		$(".price-cost__num1").css("display", "none");
		$(".price-cost__num3").css("display", "none");
		$(".price-cost__num4").css("display", "none");
		$(".price-cost__num5").css("display", "none");
		$(".price-cost__num6").css("display", "none");
		$(".price-cost__num7").css("display", "none");
		$(".price-cost__num8").css("display", "none");
		$(".price-cost__num9").css("display", "none");
		$(".price-cost__num10").css("display", "none");
		$(".price-list__item2").toggleClass("price-item");
		$(".price-list__item1").removeClass("price-item");
		$(".price-list__item3").removeClass("price-item");
		$(".price-list__item4").removeClass("price-item");
		$(".price-list__item5").removeClass("price-item");
		$(".price-list__item6").removeClass("price-item");
		$(".price-list__item7").removeClass("price-item");
		$(".price-list__item8").removeClass("price-item");
		$(".price-list__item9").removeClass("price-item");
		$(".price-list__item10").removeClass("price-item");
	});
	$('.price-list__item3').click(function () {
		$(".price-cost__num3").css("display", "flex");
		$(".price-cost__num1").css("display", "none");
		$(".price-cost__num2").css("display", "none");
		$(".price-cost__num4").css("display", "none");
		$(".price-cost__num5").css("display", "none");
		$(".price-cost__num6").css("display", "none");
		$(".price-cost__num7").css("display", "none");
		$(".price-cost__num8").css("display", "none");
		$(".price-cost__num9").css("display", "none");
		$(".price-cost__num10").css("display", "none");
		$(".price-list__item3").toggleClass("price-item");
		$(".price-list__item1").removeClass("price-item");
		$(".price-list__item2").removeClass("price-item");
		$(".price-list__item4").removeClass("price-item");
		$(".price-list__item5").removeClass("price-item");
		$(".price-list__item6").removeClass("price-item");
		$(".price-list__item7").removeClass("price-item");
		$(".price-list__item8").removeClass("price-item");
		$(".price-list__item9").removeClass("price-item");
		$(".price-list__item10").removeClass("price-item");
	});
	$('.price-list__item4').click(function () {
		$(".price-cost__num4").css("display", "flex");
		$(".price-cost__num1").css("display", "none");
		$(".price-cost__num2").css("display", "none");
		$(".price-cost__num3").css("display", "none");
		$(".price-cost__num5").css("display", "none");
		$(".price-cost__num6").css("display", "none");
		$(".price-cost__num7").css("display", "none");
		$(".price-cost__num8").css("display", "none");
		$(".price-cost__num9").css("display", "none");
		$(".price-cost__num10").css("display", "none");
		$(".price-list__item4").toggleClass("price-item");
		$(".price-list__item1").removeClass("price-item");
		$(".price-list__item2").removeClass("price-item");
		$(".price-list__item3").removeClass("price-item");
		$(".price-list__item5").removeClass("price-item");
		$(".price-list__item6").removeClass("price-item");
		$(".price-list__item7").removeClass("price-item");
		$(".price-list__item8").removeClass("price-item");
		$(".price-list__item9").removeClass("price-item");
		$(".price-list__item10").removeClass("price-item");
	});
	$('.price-list__item5').click(function () {
		$(".price-cost__num5").css("display", "flex");
		$(".price-cost__num2").css("display", "none");
		$(".price-cost__num3").css("display", "none");
		$(".price-cost__num4").css("display", "none");
		$(".price-cost__num1").css("display", "none");
		$(".price-cost__num6").css("display", "none");
		$(".price-cost__num7").css("display", "none");
		$(".price-cost__num8").css("display", "none");
		$(".price-cost__num9").css("display", "none");
		$(".price-cost__num10").css("display", "none");
		$(".price-list__item5").toggleClass("price-item");
		$(".price-list__item2").removeClass("price-item");
		$(".price-list__item3").removeClass("price-item");
		$(".price-list__item4").removeClass("price-item");
		$(".price-list__item1").removeClass("price-item");
		$(".price-list__item6").removeClass("price-item");
		$(".price-list__item7").removeClass("price-item");
		$(".price-list__item8").removeClass("price-item");
		$(".price-list__item9").removeClass("price-item");
		$(".price-list__item10").removeClass("price-item");
	});
	$('.price-list__item6').click(function () {
		$(".price-cost__num6").css("display", "flex");
		$(".price-cost__num2").css("display", "none");
		$(".price-cost__num3").css("display", "none");
		$(".price-cost__num4").css("display", "none");
		$(".price-cost__num5").css("display", "none");
		$(".price-cost__num1").css("display", "none");
		$(".price-cost__num7").css("display", "none");
		$(".price-cost__num8").css("display", "none");
		$(".price-cost__num9").css("display", "none");
		$(".price-cost__num10").css("display", "none");
		$(".price-list__item6").toggleClass("price-item");
		$(".price-list__item2").removeClass("price-item");
		$(".price-list__item3").removeClass("price-item");
		$(".price-list__item4").removeClass("price-item");
		$(".price-list__item5").removeClass("price-item");
		$(".price-list__item1").removeClass("price-item");
		$(".price-list__item7").removeClass("price-item");
		$(".price-list__item8").removeClass("price-item");
		$(".price-list__item9").removeClass("price-item");
		$(".price-list__item10").removeClass("price-item");
	});
	$('.price-list__item7').click(function () {
		$(".price-cost__num7").css("display", "flex");
		$(".price-cost__num2").css("display", "none");
		$(".price-cost__num3").css("display", "none");
		$(".price-cost__num4").css("display", "none");
		$(".price-cost__num5").css("display", "none");
		$(".price-cost__num6").css("display", "none");
		$(".price-cost__num1").css("display", "none");
		$(".price-cost__num8").css("display", "none");
		$(".price-cost__num9").css("display", "none");
		$(".price-cost__num10").css("display", "none");
		$(".price-list__item7").toggleClass("price-item");
		$(".price-list__item2").removeClass("price-item");
		$(".price-list__item3").removeClass("price-item");
		$(".price-list__item4").removeClass("price-item");
		$(".price-list__item5").removeClass("price-item");
		$(".price-list__item6").removeClass("price-item");
		$(".price-list__item1").removeClass("price-item");
		$(".price-list__item8").removeClass("price-item");
		$(".price-list__item9").removeClass("price-item");
		$(".price-list__item10").removeClass("price-item");
	});
	$('.price-list__item8').click(function () {
		$(".price-cost__num8").css("display", "flex");
		$(".price-cost__num2").css("display", "none");
		$(".price-cost__num3").css("display", "none");
		$(".price-cost__num4").css("display", "none");
		$(".price-cost__num5").css("display", "none");
		$(".price-cost__num6").css("display", "none");
		$(".price-cost__num7").css("display", "none");
		$(".price-cost__num1").css("display", "none");
		$(".price-cost__num9").css("display", "none");
		$(".price-cost__num10").css("display", "none");
		$(".price-list__item8").toggleClass("price-item");
		$(".price-list__item2").removeClass("price-item");
		$(".price-list__item3").removeClass("price-item");
		$(".price-list__item4").removeClass("price-item");
		$(".price-list__item5").removeClass("price-item");
		$(".price-list__item6").removeClass("price-item");
		$(".price-list__item7").removeClass("price-item");
		$(".price-list__item1").removeClass("price-item");
		$(".price-list__item9").removeClass("price-item");
		$(".price-list__item10").removeClass("price-item");
	});
	$('.price-list__item9').click(function () {
		$(".price-cost__num9").css("display", "flex");
		$(".price-cost__num2").css("display", "none");
		$(".price-cost__num3").css("display", "none");
		$(".price-cost__num4").css("display", "none");
		$(".price-cost__num5").css("display", "none");
		$(".price-cost__num6").css("display", "none");
		$(".price-cost__num7").css("display", "none");
		$(".price-cost__num8").css("display", "none");
		$(".price-cost__num1").css("display", "none");
		$(".price-cost__num10").css("display", "none");
		$(".price-list__item9").toggleClass("price-item");
		$(".price-list__item2").removeClass("price-item");
		$(".price-list__item3").removeClass("price-item");
		$(".price-list__item4").removeClass("price-item");
		$(".price-list__item5").removeClass("price-item");
		$(".price-list__item6").removeClass("price-item");
		$(".price-list__item7").removeClass("price-item");
		$(".price-list__item8").removeClass("price-item");
		$(".price-list__item1").removeClass("price-item");
		$(".price-list__item10").removeClass("price-item");
	});
	$('.price-list__item10').click(function () {
		$(".price-cost__num10").css("display", "flex");
		$(".price-cost__num2").css("display", "none");
		$(".price-cost__num3").css("display", "none");
		$(".price-cost__num4").css("display", "none");
		$(".price-cost__num5").css("display", "none");
		$(".price-cost__num6").css("display", "none");
		$(".price-cost__num7").css("display", "none");
		$(".price-cost__num8").css("display", "none");
		$(".price-cost__num9").css("display", "none");
		$(".price-cost__num1").css("display", "none");
		$(".price-list__item10").toggleClass("price-item");
		$(".price-list__item2").removeClass("price-item");
		$(".price-list__item3").removeClass("price-item");
		$(".price-list__item4").removeClass("price-item");
		$(".price-list__item5").removeClass("price-item");
		$(".price-list__item6").removeClass("price-item");
		$(".price-list__item7").removeClass("price-item");
		$(".price-list__item8").removeClass("price-item");
		$(".price-list__item9").removeClass("price-item");
		$(".price-list__item1").removeClass("price-item");
	});


});